import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Parser, AstBuilder, GherkinClassicTokenMatcher } from '@cucumber/gherkin';
import { runPrdc, makePrd, cleanup, VALID_META, VALID_REQS } from './helpers.mjs';

// Phase 1 m3: `prdc build gherkin` compiles requirements.yaml into a single
// .feature file: one tagged Scenario per requirement, one `*` step per
// acceptance criterion. Free-text ACs carry no Given/When/Then semantics,
// so the neutral `*` keyword keeps the file valid Gherkin without inventing
// structure. Tests parse the output with the reference Gherkin parser.

let nodeId = 0;
function parse(text) {
  const parser = new Parser(new AstBuilder(() => nodeId++), new GherkinClassicTokenMatcher());
  return parser.parse(text);
}

describe('build gherkin', () => {
  it('writes a feature file named after the PRD with a Feature header', () => {
    const dir = makePrd({ 'meta.yaml': VALID_META, 'requirements.yaml': VALID_REQS });
    const r = runPrdc(['build', 'gherkin', dir]);
    expect(r.status).toBe(0);
    const text = readFileSync(join(dir, 'build.feature'), 'utf8');
    expect(text).toContain('Feature: Test Feature');
    expect(text.startsWith('# Generated by prdc build gherkin from PRD-9001')).toBe(true);
    cleanup(dir);
  });

  it('emits one tagged Scenario per requirement, steps from acceptance criteria', () => {
    const dir = makePrd({ 'meta.yaml': VALID_META, 'requirements.yaml': VALID_REQS });
    runPrdc(['build', 'gherkin', dir]);
    const text = readFileSync(join(dir, 'build.feature'), 'utf8');
    expect(text).toContain('@FR-01 @P1');
    expect(text).toContain('Scenario: FR-01: a working checkout');
    expect(text).toContain('* checkout completes with one tap');
    cleanup(dir);
  });

  it('produces output the reference Gherkin parser accepts', () => {
    const dir = makePrd({ 'meta.yaml': VALID_META, 'requirements.yaml': VALID_REQS });
    runPrdc(['build', 'gherkin', dir]);
    const text = readFileSync(join(dir, 'build.feature'), 'utf8');
    const ast = parse(text);
    expect(ast.feature.children).toHaveLength(1);
    expect(ast.feature.children[0].scenario.name).toBe('FR-01: a working checkout');
    cleanup(dir);
  });

  it('accepts the checkout sample: every requirement becomes a parseable scenario', () => {
    const dir = makePrd({});
    const out = join(dir, 'out.feature');
    const r = runPrdc(['build', 'gherkin', 'sample/checkout-redesign', '--out', out]);
    expect(r.status).toBe(0);
    const text = readFileSync(out, 'utf8');
    const ast = parse(text);
    const names = ast.feature.children.map(c => c.scenario.name);
    expect(names).toContain('FR-01: my saved card to appear pre-selected at checkout');
    expect(names).toContain('NFR-02: explicit consent capture for card storage');
    expect(ast.feature.children).toHaveLength(5);
    cleanup(dir);
  });

  it('honors a custom --out path', () => {
    const dir = makePrd({ 'meta.yaml': VALID_META, 'requirements.yaml': VALID_REQS });
    const out = join(dir, 'custom-name.feature');
    const r = runPrdc(['build', 'gherkin', dir, '--out', out]);
    expect(r.status).toBe(0);
    expect(readFileSync(out, 'utf8')).toContain('Feature: Test Feature');
    cleanup(dir);
  });

  it('fails like the other build targets when meta.yaml is missing', () => {
    const dir = makePrd({ 'requirements.yaml': VALID_REQS });
    const r = runPrdc(['build', 'gherkin', dir]);
    expect(r.status).toBe(1);
    expect(r.output).toContain('missing meta.yaml');
    cleanup(dir);
  });
});
